CREATE TABLE `company`
(
    `id`        bigint       NOT NULL,
    `code`      varchar(255) NOT NULL,
    `countryId` bigint       NOT NULL,
    `name`      varchar(255) NOT NULL,
    `sample`    bit(1)       NOT NULL,
    `type`      enum('IT_PRODUCT_BASE','IT_PROJECT_BASE','OTHERS') NOT NULL,

    CREATE TABLE `companycalendar` (
        `id` bigint NOT NULL,
        `companyId` bigint NOT NULL,
        `endDate` date NOT NULL,
        `eventName` varchar (255) NOT NULL,
        `eventType` enum('COMPANY_EVENT','HOLIDAY','MEETING','WORKDAY') NOT NULL,
        `recurring` bit (1) NOT NULL,
        `startDate` date NOT NULL,
        CREATE TABLE `companyweekend` (
        `id` bigint NOT NULL,
        `companyId` bigint NOT NULL,
        `day` enum('FRIDAY','MONDAY','SATURDAY','SUNDAY','THURSDAY','TUESDAY','WEDNESDAY') NOT NULL,
        CREATE TABLE `companyworkinghour` (
        `id` bigint NOT NULL,
        `companyId` bigint NOT NULL,
        `dayOfWeek` enum('FRIDAY','MONDAY','SATURDAY','SUNDAY','THURSDAY','TUESDAY','WEDNESDAY') DEFAULT NULL,
        `description` varchar (255) NOT NULL,
        `endDate` date DEFAULT NULL,
        `eventDate` date DEFAULT NULL,
        `minutes` int NOT NULL,
        `recurring` bit (1) NOT NULL,
        `scope` enum('DATE_RANGE','DEFAULT','SPECIFIC_DATE','WEEK_DAY') NOT NULL,
        `startDate` date DEFAULT NULL,
        CREATE TABLE `component` (
        `id` bigint NOT NULL,
        `companyId` bigint NOT NULL,
        `name` varchar (255) NOT NULL,
        CREATE TABLE `contactus` (
        `id` bigint NOT NULL,
        `addressed` bit (1) NOT NULL,
        `companyId` bigint DEFAULT NULL,
        `details` varchar (255) NOT NULL,
        `email` varchar (255) NOT NULL,
        `name` varchar (255) NOT NULL,
        `subject` varchar (255) NOT NULL,
        CREATE TABLE `country` (
        `id` bigint NOT NULL,
        `countryCode` varchar (255) NOT NULL,
        `countryCode3` varchar (255) NOT NULL,
        `currency` varchar (255) DEFAULT NULL,
        `flag` varchar (255) DEFAULT NULL,
        `language` varchar (255) DEFAULT NULL,
        `name` varchar (255) NOT NULL,
        `phoneCode` varchar (5000) NOT NULL,
        `region` varchar (255) DEFAULT NULL,
        `subRegion` varchar (255) DEFAULT NULL,
        CREATE TABLE `designation` (
        `id` bigint NOT NULL,
        `companyId` bigint NOT NULL,
        `name` varchar (255) NOT NULL,
        `roleId` bigint DEFAULT NULL,
        CREATE TABLE `role` (
        `id` bigint NOT NULL,
        `code` enum('ADMIN','HR','PM','TR') NOT NULL,
        `companyId` bigint NOT NULL,
        `name` varchar (255) NOT NULL,
        `required` bit (1) NOT NULL,
        `systemRole` bit (1) NOT NULL,
        CREATE TABLE `priority` (
        `id` bigint NOT NULL,
        `companyId` bigint NOT NULL,
        `name` varchar (255) NOT NULL,
        `priorityLevel` int NOT NULL,
        CREATE TABLE `resource` (
        `id` bigint NOT NULL,
        `companyId` bigint NOT NULL,
        `countryId` bigint NOT NULL,
        `dateOfBirth` date DEFAULT NULL,
        `designationId` bigint DEFAULT NULL,
        `email` varchar (255) NOT NULL,
        `individualCapacity` bit (1) NOT NULL,
        `lastWorkingDate` date DEFAULT NULL,
        `isLead` bit (1) NOT NULL,
        `leadResourceId` bigint DEFAULT NULL,
        `mobileNumber` varchar (255) DEFAULT NULL,
        `name` varchar (255) NOT NULL,
        `password` varchar (255) NOT NULL,
        `roleId` bigint DEFAULT NULL,
        `status` enum('ACTIVE','INACTIVE') NOT NULL,
        CREATE TABLE `resourceleave` (
        `id` bigint NOT NULL,
        `approvedAt` datetime(6) DEFAULT NULL,
        `approvedBy` bigint DEFAULT NULL,
        `days` double DEFAULT NULL,
        `endDate` date NOT NULL,
        `leaveType` enum('ANNUAL_LEAVE','CASUAL_LEAVE','COMPENSATION_LEAVE','SHORT_LEAVE','SICK_LEAVE') NOT NULL,
        `reason` varchar (255) DEFAULT NULL,
        `resourceId` bigint NOT NULL,
        `startDate` date NOT NULL,
        `status` enum('APPROVED','PENDING','REJECTED') NOT NULL,
        CREATE TABLE `entitydetail` (
        `detailType` enum('ATTACHED_FILE','URL','DISCUSSION') NOT NULL,
        `details` varchar (255) DEFAULT NULL,
        `entityId` bigint NOT NULL,
        `entityType` enum('COMPANY','PRODUCT','RELEASE','RESOURCE','CONCERN') NOT NULL,
        CREATE TABLE `epic` (
        `id` bigint NOT NULL,
        `code` varchar (255) NOT NULL,
        `comments` varchar (255) DEFAULT NULL,
        `componentId` bigint DEFAULT NULL,
        `dependOnEpicId` bigint DEFAULT NULL,
        `details` varchar (255) DEFAULT NULL,
        `endDate` date DEFAULT NULL,
        `forcefullyAdded` bit (1) NOT NULL,
        `priorityId` bigint DEFAULT NULL,
        `productId` bigint NOT NULL,
        `raisedByResourceId` bigint DEFAULT NULL,
        `releaseId` bigint DEFAULT NULL,
        `replicate` bit (1) NOT NULL,
        `replicatedById` bigint DEFAULT NULL,
        `requiredBy` date DEFAULT NULL,
        `risks` varchar (255) DEFAULT NULL,
        `startDate` date DEFAULT NULL,
        `status` enum('DELETED','OPEN','REOPEN','RESOLVED') NOT NULL,
        `title` varchar (255) NOT NULL,
        `valueGain` double NOT NULL,
        CREATE TABLE `epicdetail` (
        `id` bigint NOT NULL,
        `detailType` enum('ATTACHED_FILE','COMMENT','REFERENCE','URL') NOT NULL,
        `details` varchar (255) DEFAULT NULL,
        `epicId` bigint NOT NULL,
        `link` varchar (255) DEFAULT NULL,
        `name` varchar (255) DEFAULT NULL,
        CREATE TABLE `epiclink` (
        `id` bigint NOT NULL,
        `details` varchar (255) DEFAULT NULL,
        `epicId` bigint NOT NULL,
        `linkType` enum('DEPEND_ON','RELATED_TO') NOT NULL,
        `linkedEpicId` bigint NOT NULL,
        CREATE TABLE `epicestimate` (
        `id` bigint NOT NULL,
        `epicId` bigint NOT NULL,
        `estimate` int NOT NULL,
        `resources` int NOT NULL,
        `roleId` bigint NOT NULL,
        CREATE TABLE `epicassignment` (
        `id` bigint NOT NULL,
        `changedManually` bit (1) NOT NULL,
        `epicId` bigint NOT NULL,
        `estimate` int NOT NULL,
        `expectedDeliveryDate` date DEFAULT NULL,
        `releaseId` bigint NOT NULL,
        `resourceId` bigint NOT NULL,
        `roleId` bigint NOT NULL,
        `status` enum('COMPLETED','ON_HOLD','OPEN','OVERDUE','STARTED') NOT NULL,
        CREATE TABLE `product` (
        `id` bigint NOT NULL,
        `code` varchar (255) NOT NULL,
        `companyId` bigint NOT NULL,
        `endDate` date DEFAULT NULL,
        `name` varchar (255) NOT NULL,
        `otherActivitiesPercentTime` int NOT NULL,
        `productManagerId` bigint NOT NULL,
        `releaseIteration` enum('ANNUAL','BI_MONTHLY','BI_WEEKLY','MONTHLY','QUARTERLY','SEMI_ANNUAL','TRI_WEEKLY','WEEKLY') NOT NULL,
        `startDate` date NOT NULL,
        CREATE TABLE `productresource` (
        `id` bigint NOT NULL,
        `participationPercentTime` int NOT NULL,
        `productId` bigint NOT NULL,
        `resourceId` bigint NOT NULL,
        `roleId` bigint NOT NULL,
        CREATE TABLE `releases` (
        `id` bigint NOT NULL,
        `endDate` date NOT NULL,
        `name` varchar (255) NOT NULL,
        `productId` bigint NOT NULL,
        `startDate` date NOT NULL,
        `status` enum('COMPLETED','OVERDUE','PLANNED','STARTED','UNPLANNED') NOT NULL,
        `version` int NOT NULL,
        `workingDays` int NOT NULL,
        CREATE TABLE `releasestatus` (
        `id` bigint NOT NULL,
        `code` enum('COMPLETED','OVERDUE','PLANNED','STARTED','UNPLANNED') NOT NULL,
        `name` varchar (255) NOT NULL,
        CREATE TABLE `releaseworkingday` (
        `id` bigint NOT NULL,
        `minutes` int NOT NULL,
        `releaseId` bigint NOT NULL,
        `workingDate` date NOT NULL,
        CREATE TABLE `releaseepichistory` ( -- On Start Release
        `id` bigint NOT NULL,
        `comments` varchar (255) DEFAULT NULL,
        `epicId` bigint NOT NULL,
        `forcefullyAdded` bit (1) NOT NULL,
        `releaseId` bigint NOT NULL,
        `risks` varchar (255) DEFAULT NULL,
        CREATE TABLE `releaseresource` (    -- -- On Start Release
        `id` bigint NOT NULL,
        `participationPercentTime` int NOT NULL,
        `releaseId` bigint NOT NULL,
        `resourceId` bigint NOT NULL,
        `roleId` bigint NOT NULL,
        CREATE TABLE `epicreleaseconcern` (
        `id` bigint NOT NULL,
        `assignedToResourceId` bigint NOT NULL,
        `epicId` bigint NOT NULL,
        `releaseId` bigint NOT NULL,
        `status` enum('ANSWERED','CLOSED','OPEN','RESOLVED') NOT NULL,
        `title` varchar (255) NOT NULL,
        CREATE TABLE `timelogging` (
        `id` bigint NOT NULL,
        `comments` varchar (255) DEFAULT NULL,
        `epicId` bigint NOT NULL,
        `loggedForDate` date DEFAULT NULL,
        `minutes` int NOT NULL,
        `releaseId` bigint NOT NULL,
        `resourceId` bigint NOT NULL,